import React,{useEffect} from "react"
import { MDBDataTable } from "mdbreact"
import { Row, Col, Card, CardBody, CardTitle } from "reactstrap"

import { connect } from "react-redux";

//Import Action to copy breadcrumb items from local state to redux state
import { setBreadcrumbItems } from "../../store/actions";

import "./datatables.scss"

const DatatableTables = (props) => {
  document.title = "Data Table | Lexa - Responsive Bootstrap 5 Admin Dashboard";

  
  const breadcrumbItems = [
    { title: "Lexa", link: "#" },
    { title: "Tables", link: "#" },
    { title: "Data Tables", link: "#" },
  ]

  useEffect(() => {
    props.setBreadcrumbItems('Data Tables', breadcrumbItems)
  })

  const data = {
    columns: [
      {
        label: "Roll number",
        field: "roll number",
        sort: "asc",
        width: 150,
      },
      {
        label: "Student name",
        field: "student name",
        sort: "asc",
        width: 270,
      },
      {
        label: "College",
        field: "college",
        sort: "asc",
        width: 200,
      },
      {
        label: "Branch",
        field: "branch",
        sort: "asc",
        width: 100,
      },
      {
      label: "Passout year",
        field: "passout year",
        sort: "asc",
        width: 150,
      },
      {
        label: "SSC percentage",
          field: "ssc percentage ",
          sort: "asc",
          width: 150,
        },
        {
          label: "Inter percentage",
            field: "inter percentage ",
            sort: "asc",
            width: 150,
          },
          {
            label: "Diploma percentage",
              field: "diploma percentage ",
              sort: "asc",
              width: 150,
            },
        {
          label: "Btech_percentage",
            field: "btech percentage",
            sort: "asc",
            width: 150,
          },
      {
        label: "Gender",
        field: "gender",
        sort: "asc",
        width: 150,
      },
      {
        label: "Mobile",
        field: "mobile",
        sort: "asc",
        width: 150,
      },
      {
        label: "Email",
        field: "email",
        sort: "asc",
        width: 150,
      },
      {
        label: "Official_mail",
        field: "official_mail",
        sort: "asc",
        width: 150,
      },
      {
        label: "Scholarship",
        field: "scholarship",
        sort: "asc",
        width: 150,
      },
  
  
    ],
    rows: [
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0502",
        student_name: "AKULA SRI SAI PRAVALLIKA",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "92.9",
        diploma_percentage:"",
        btech_percentage:"64.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0503",
        student_name: "AMAN RAJ",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "100",
        inter_percentage: "66",
        diploma_percentage:"56.5",
        btech_percentage:"57.5",
        backlogs:"3",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0504",
        student_name: "ANNABATHULA VENKATESH",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"80.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0505",
        student_name: "BANDRU SAI SPANDANA",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "79.17",
        inter_percentage: "83.7",
        diploma_percentage:"",
        btech_percentage:"65.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0506",
        student_name: "BAVARAJU NITHIN SAI",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "83.33",
        inter_percentage: "76.7",
        diploma_percentage:"56.5",
        btech_percentage:"57.5",
        backlogs:"2",
        gender:"FEMale",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0507",
        student_name: "BEZAWADA TANUJA",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "90",
        inter_percentage: "95.1",
        diploma_percentage:"94.87",
        btech_percentage:"70.5",
        backlogs:"0",
        gender:"FEMale",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0508",
        student_name: "BOGGAVARAPU SUGUNA SRIKANYA MANOJNA",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "93.2",
        diploma_percentage:"",
        btech_percentage:"74.5",
        backlogs:"0",
        gender:"FEMale",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0509",
        student_name: "BORRA SRINIVASA MANIKANTA",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "90",
        inter_percentage: "72",
        diploma_percentage:"",
        btech_percentage:"45.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0510",
        student_name: "BUDDA BALA ATYUTHI SRI SAI",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "88.33",
        inter_percentage: "94.2",
        diploma_percentage:"96.17",
        btech_percentage:"57.5",
        backlogs:"1",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      {
        roll_number:"18A91A0501",
        student_name: "ADABALA HARI BHASKAR",
        college: "AEC",
        branch: "CSE",
        passout_year: "2022",
        ssc_percentage: "93.3",
        inter_percentage: "96.5",
        diploma_percentage:"97.83",
        btech_percentage:"57.5",
        backlogs:"0",
        gender:"Male",
        mobile:"123456",
        email:"testing@gmail.com",
        official_mail:"testing@gmail.com",
        scholarship:"Yes",

      
      },
      
      

      
      
      

      

      
      
      
      
   ],
  }

  return (
    <React.Fragment>

          <Row>
            <Col className="col-12">
              <Card>
                <CardBody>
                  <CardTitle className="h4">Default Datatable </CardTitle>
                  <p className="card-title-desc">
                    mdbreact DataTables has most features enabled by default, so
                    all you need to do to use it with your own tables is to call
                    the construction function:{" "}
                    <code>&lt;MDBDataTable /&gt;</code>.
                  </p>

                  <MDBDataTable responsive bordered data={data} />
                </CardBody>
              </Card>
            </Col>
          </Row>

          <Row>
            <Col className="col-12">
              <Card>
                <CardBody>
                  <CardTitle className="h4">Stripped example </CardTitle>
                  <p className="card-title-desc">
                    mdbreact DataTables has most features enabled by default, so
                    all you need to do to use it with your own tables is to call
                    the construction function:{" "}
                    <code>&lt;MDBDataTable striped /&gt;</code>.
                  </p>

                  <MDBDataTable responsive striped bordered data={data} />
                </CardBody>
              </Card>
            </Col>
          </Row>
        
    </React.Fragment>
  )
}

export default connect(null, { setBreadcrumbItems })(DatatableTables);